
#ifndef _SMS_PROVIDER_H_
#define _SMS_PROVIDER_H_

#include "mmssms_db_helper.h"

#define SMS_PROVIDER_ID   "sms"

//define  DESTINATION


#define SMS_PROVIDER_DESTINATION_LIST   			0


#define SMS_PROVIDER_COL_ID 						SMS_TABLE_COL_ID 
#define SMS_PROVIDER_COL_THREAD_ID				SMS_TABLE_COL_THREAD_ID   
#define SMS_PROVIDER_COL_TYPE 						SMS_TABLE_COL_TYPE
#define SMS_PROVIDER_COL_ADDRESS 					SMS_TABLE_COL_ADDRESS
#define SMS_PROVIDER_COL_DATE 					SMS_TABLE_COL_DATE
#define SMS_PROVIDER_COL_PROTOCAL 				SMS_TABLE_COL_PROTOCAL
#define SMS_PROVIDER_COL_READ 					SMS_TABLE_COL_READ
#define SMS_PROVIDER_COL_STATUS 					SMS_TABLE_COL_STATUS
#define SMS_PROVIDER_COL_REPLY_PATH_PRESENT 	SMS_TABLE_COL_REPLY_PATH_PRESENT
#define SMS_PROVIDER_COL_BODY 					SMS_TABLE_COL_BODY
#define SMS_PROVIDER_COL_NAME 					"name"  //VIRTUAL COL: contact col, better to refer to contact macro 


#define SMS_PROVIDER_DESTINATION_CONVERSATION   			1

#define SMS_PROVIDER_COL_GROUP_NAME						       "name"  //VIRTUAL COL: contact col, better to refer to contact macro
#define SMS_PROVIDER_COL_CACHED_NAME						SMS_THREADS_TABLE_COL_CACHED_NAME
#define SMS_PROVIDER_COL_LAST_MODIFY_DATE					SMS_THREADS_TABLE_COL_DATE
#define SMS_PROVIDER_COL_CANONICAL_ADDRESS					SMS_THREADS_TABLE_COL_ADDRESS
#define SMS_PROVIDER_COL_MESSAGE_COUNT						SMS_THREADS_TABLE_COL_MESSAGE_COUNT
#define SMS_PROVIDER_COL_UNREAD_MESSAGE_COUNT				SMS_THREADS_TABLE_COL_UNREAD_COUNT
#define SMS_PROVIDER_COL_FAILED_MESSAGE_COUNT				SMS_THREADS_TABLE_COL_FAILED_COUNT


//#define SMS_PROVIDER_DESTINATION_ADDRESS_CONVERSATION   			2

#endif
